# Generated by Django 5.2.1 on 2025-05-27 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eisa_id', models.CharField(max_length=20, unique=True)),
                ('qualification', models.CharField(max_length=100)),
                ('paper', models.CharField(max_length=10)),
                ('saqa_id', models.CharField(blank=True, max_length=20, null=True)),
                ('moderator', models.CharField(blank=True, max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to='assessments/')),
                ('memo', models.FileField(blank=True, null=True, upload_to='assessments/memos/')),
                ('comment', models.TextField(blank=True)),
                ('forward_to_moderator', models.BooleanField(default=False)),
                ('moderator_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Submitted to Moderator', 'Submitted to Moderator'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Submitted', 'Submitted'), ('Not Sent', 'Not Sent')], default='Pending', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('marks', models.PositiveIntegerField()),
                ('case_study', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_questions', to='core.assessment')),
            ],
        ),
    ]
