# Generated by Django 5.2.1 on 2025-07-05 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examnode',
            name='content',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='examnode',
            name='data_uri',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='examnode',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
