# Generated by Django 5.2.1 on 2025-08-04 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualification',
            name='code',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='description',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='level',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='qualification_type',
        ),
        migrations.AlterField(
            model_name='qualification',
            name='name',
            field=models.CharField(choices=[('Maintenance Planner 1A', 'Maintenance Planner 1A'), ('Maintenance Planner 1B', 'Maintenance Planner 1B'), ('Maintenance Planner 1C', 'Maintenance Planner 1C'), ('Quality Controller 2A', 'Quality Controller 2A'), ('Quality Controller 2B', 'Quality Controller 2B'), ('Quality Controller 2C', 'Quality Controller 2C'), ('Chemical Plant 1A', 'Chemical Plant 1A'), ('Chemical Plant 1B', 'Chemical Plant 1B'), ('Chemical Plant 1C', 'Chemical Plant 1C'), ('Chemical Plant 2A', 'Chemical Plant 2A'), ('Chemical Plant 2B', 'Chemical Plant 2B'), ('Chemical Plant 2C', 'Chemical Plant 2C'), ('Chemical Plant 3A', 'Chemical Plant 3A'), ('Chemical Plant 3B', 'Chemical Plant 3B'), ('Chemical Plant 3C', 'Chemical Plant 3C')], max_length=100, unique=True),
        ),
    ]
