# Generated by Django 5.2.1 on 2025-08-04 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_qualification_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='paper',
            field=models.CharField(max_length=50),
        ),
    ]
