# Generated by Django 5.2.1 on 2025-06-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_assessment_qualification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualification',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='qualification',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='qualification',
            name='level',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
