# Generated by Django 5.2.1 on 2025-06-04 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_casestudy_questionbankentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedquestion',
            name='case_study',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.casestudy'),
        ),
    ]
