# Generated by Django 5.2.1 on 2025-07-06 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_examnode_content_examnode_data_uri_examnode_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='examnode',
            name='paper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.paper'),
        ),
    ]
