# Generated by Django 5.2.1 on 2025-06-09 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_generatedquestion_case_study'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='assessment',
            name='qcto_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Submitted to Moderator', 'Submitted to Moderator'), ('Returned for Changes', 'Returned for Changes'), ('Approved by Moderator', 'Approved by Moderator'), ('Submitted to ETQA', 'Submitted to ETQA'), ('Approved by ETQA', 'Approved by ETQA'), ('Rejected', 'Rejected')], default='Pending', max_length=30),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_user', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Revised', 'Revised'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='core.assessment')),
            ],
        ),
    ]
