# Generated by Django 5.2.1 on 2025-07-06 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_examnode_paper'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='paper_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='core.paper'),
        ),
    ]
