# Generated by Django 5.2.1 on 2025-06-14 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_qualification_code_qualification_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_assessments', to=settings.AUTH_USER_MODEL),
        ),
    ]
