# Generated by Django 5.2.1 on 2025-08-04 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_assessment_paper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='module_number',
            field=models.CharField(choices=[('1A', 'Module 1A'), ('1B', 'Module 1B'), ('1C', 'Module 1C'), ('2A', 'Module 2A'), ('2B', 'Module 2B'), ('2C', 'Module 2C'), ('3A', 'Module 3A'), ('3B', 'Module 3B'), ('3C', 'Module 3C')], default='1A', help_text='Module identifier (1A, 1B, etc)', max_length=2),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='name',
            field=models.CharField(choices=[('Maintenance Planner', 'Maintenance Planner'), ('Quality Controller', 'Quality Controller'), ('Chemical Plant', 'Chemical Plant')], max_length=100, unique=True),
        ),
    ]
