# Generated by Django 5.2.1 on 2025-07-14 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_assessment_paper_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='questions_randomized',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('marks', models.PositiveIntegerField(default=0)),
                ('content_html', models.TextField(blank=True, help_text='Paste question text, tables, images (HTML) here.')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.assessment')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.questionbankentry')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('assessment', 'question')},
            },
        ),
        migrations.AddField(
            model_name='assessment',
            name='questions',
            field=models.ManyToManyField(related_name='assessments', through='core.AssessmentQuestion', to='core.questionbankentry'),
        ),
    ]
