# Generated by Django 5.2.1 on 2025-06-10 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_checklistitem_assessment_qcto_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbankentry',
            name='question_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('case_study', 'Case Study'), ('mcq', 'Multiple Choice')], default='standard', max_length=20),
        ),
        migrations.AlterField(
            model_name='questionbankentry',
            name='case_study',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.casestudy'),
        ),
        migrations.AlterField(
            model_name='questionbankentry',
            name='marks',
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name='MCQOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(limit_choices_to={'question_type': 'mcq'}, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='core.questionbankentry')),
            ],
        ),
    ]
