# Generated by Django 5.2.1 on 2025-06-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_assessment_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('default', 'Awaiting Activation'), ('admin', 'Administrator'), ('assessor_dev', 'Assessor (Developer)'), ('moderator', 'Moderator (Developer)'), ('qcto', 'QCTO Validator'), ('etqa', 'ETQA'), ('learner', 'Learner'), ('assessor_marker', 'Assessor (Marker)'), ('internal_mod', 'Internal Moderator'), ('external_mod', 'External Moderator (QALA)')], default='learner', max_length=30),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='qualification_type',
            field=models.CharField(choices=[('default', 'Not Yet Assigned'), ('Maintenance Planner', 'Maintenance Planner'), ('Quality Controller', 'Quality Controller'), ('Chemical Plant', 'Chemical Plant')], default='Chemical Plant', max_length=50),
        ),
    ]
