# Generated by Django 5.2.1 on 2025-08-06 19:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_assessment_module_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extractedquestion',
            name='source_paper',
        ),
        migrations.RemoveField(
            model_name='questionchild',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='questioncontent',
            name='child_block',
        ),
        migrations.RemoveField(
            model_name='questioncontent',
            name='parent_block',
        ),
        migrations.RemoveField(
            model_name='questionitem',
            name='node',
        ),
        migrations.RemoveField(
            model_name='questionparent',
            name='paper',
        ),
        migrations.DeleteModel(
            name='QuestionPoolEntry',
        ),
        migrations.AlterModelOptions(
            name='examnode',
            options={'ordering': ['order_index']},
        ),
        migrations.RemoveField(
            model_name='examnode',
            name='data_uri',
        ),
        migrations.RemoveField(
            model_name='examnode',
            name='is_top_level',
        ),
        migrations.RemoveField(
            model_name='examnode',
            name='payload',
        ),
        migrations.RemoveField(
            model_name='examnode',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='structure_json',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='total_marks',
        ),
        migrations.AddField(
            model_name='examnode',
            name='binary_content',
            field=models.BinaryField(blank=True, help_text='For storing binary data like images', null=True),
        ),
        migrations.AddField(
            model_name='examnode',
            name='content_type',
            field=models.CharField(blank=True, default='', help_text='MIME type for binary_content', max_length=50),
        ),
        migrations.AddField(
            model_name='examnode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examnode',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='examnode',
            name='content',
            field=models.JSONField(default=dict, help_text='Structured content like tables, case studies'),
        ),
        migrations.AlterField(
            model_name='examnode',
            name='id',
            field=models.CharField(default='57f3ccd001a14486adf4cba468f570d6', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='examnode',
            name='marks',
            field=models.CharField(blank=True, default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='examnode',
            name='node_type',
            field=models.CharField(choices=[('question', 'Question'), ('table', 'Table'), ('image', 'Image'), ('case_study', 'Case Study'), ('instruction', 'Instruction')], default='question', max_length=50),
        ),
        migrations.AlterField(
            model_name='examnode',
            name='number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='examnode',
            name='paper',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.paper'),
        ),
        migrations.AlterField(
            model_name='examnode',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.examnode'),
        ),
        migrations.AlterField(
            model_name='examnode',
            name='text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddIndex(
            model_name='examnode',
            index=models.Index(fields=['paper', 'order_index'], name='core_examno_paper_i_7643d7_idx'),
        ),
        migrations.AddIndex(
            model_name='examnode',
            index=models.Index(fields=['node_type'], name='core_examno_node_ty_db9434_idx'),
        ),
        migrations.AddIndex(
            model_name='examnode',
            index=models.Index(fields=['parent', 'order_index'], name='core_examno_parent__586895_idx'),
        ),
        migrations.AddConstraint(
            model_name='examnode',
            constraint=models.CheckConstraint(condition=models.Q(('node_type__in', ['question', 'table', 'image', 'case_study', 'instruction'])), name='valid_node_type'),
        ),
        migrations.DeleteModel(
            name='ExtractedQuestion',
        ),
        migrations.DeleteModel(
            name='QuestionChild',
        ),
        migrations.DeleteModel(
            name='QuestionContent',
        ),
        migrations.DeleteModel(
            name='QuestionItem',
        ),
        migrations.DeleteModel(
            name='QuestionNode',
        ),
        migrations.DeleteModel(
            name='QuestionParent',
        ),
    ]
