# Generated by Django 5.2.1 on 2025-06-16 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_customuser_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_date', models.DateField()),
                ('number_of_learners', models.PositiveIntegerField()),
                ('submitted_to_center', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.assessment')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.assessmentcentre')),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.qualification')),
            ],
        ),
    ]
