# Generated by Django 5.2.1 on 2025-08-06 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_extractedquestion_source_paper_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegexPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.TextField()),
                ('description', models.TextField()),
                ('match_score', models.FloatField()),
                ('example_usage', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='examnode',
            name='id',
            field=models.CharField(default='fe62e4a6ddd54dc89d31dce2368eaf66', max_length=32, primary_key=True, serialize=False),
        ),
    ]
