# Generated by Django 5.2.1 on 2025-07-16 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_assessment_questions_randomized_assessmentquestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examnode',
            name='is_top_level',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examnode',
            name='order_index',
            field=models.IntegerField(default=0),
        ),
    ]
