# Generated by Django 5.2.1 on 2025-07-16 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_examnode_is_top_level_examnode_order_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='structure_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
