# Generated by Django 5.2.1 on 2025-08-06 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_regexpattern_alter_examnode_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='structure_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='paper',
            name='total_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paper',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='examnode',
            name='id',
            field=models.CharField(default='0a9e79c0d0be43b892a28d8cece23fee', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paper',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='paper',
            name='qualification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.qualification'),
        ),
    ]
