# Generated by Django 5.2.1 on 2025-06-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_examanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Submitted to Moderator', 'Submitted to Moderator'), ('Returned for Changes', 'Returned for Changes'), ('Approved by Moderator', 'Approved by Moderator'), ('Submitted to QCTO', 'Submitted to QCTO'), ('Approved by QCTO', 'Approved by QCTO'), ('Submitted to ETQA', 'Submitted to ETQA'), ('Approved by ETQA', 'Approved by ETQA'), ('Rejected', 'Rejected')], default='Pending', max_length=30),
        ),
    ]
