# Generated by Django 5.2.1 on 2025-08-11 22:34

from django.db import migrations
import json


def convert_content_to_json(apps, schema_editor):
    # Get the historical version of your model
    ExamNode = apps.get_model('core', 'ExamNode')

    # Process each node
    for node in ExamNode.objects.all():
        if node.content is None:
            node.content = []
        elif isinstance(node.content, str):
            try:
                # Try to parse as JSON
                node.content = json.loads(node.content)
            except json.JSONDecodeError:
                # If not valid JSON, store as text item
                node.content = [{"type": "text", "text": node.content}]
        # Save the changes
        node.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_paper_structure_json_paper_total_marks_and_more'),
    ]

    operations = [
        migrations.RunPython(convert_content_to_json),
    ]
