# Generated by Django 5.2.1 on 2025-07-16 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_paper_structure_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='is_randomized',
            field=models.BooleanField(default=False),
        ),
    ]
