# Generated by Django 5.2.1 on 2025-06-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_assessment_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='examanswer',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='examanswer',
            name='attempt_number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='examanswer',
            unique_together={('user', 'question', 'attempt_number')},
        ),
    ]
