# Generated by Django 5.2.1 on 2025-08-12 22:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_convert_content_to_json'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='examnode',
            name='valid_node_type',
        ),
        migrations.RemoveIndex(
            model_name='examnode',
            name='core_examno_paper_i_7643d7_idx',
        ),
        migrations.RemoveIndex(
            model_name='examnode',
            name='core_examno_node_ty_db9434_idx',
        ),
        migrations.RemoveIndex(
            model_name='examnode',
            name='core_examno_parent__586895_idx',
        ),
        migrations.RemoveField(
            model_name='examnode',
            name='binary_content',
        ),
        migrations.RemoveField(
            model_name='examnode',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='examnode',
            name='is_active',
        ),
        migrations.AddField(
            model_name='examnode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='examnode',
            name='content',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='examnode',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='examnode',
            name='marks',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='examnode',
            name='node_type',
            field=models.CharField(choices=[('question', 'Question'), ('table', 'Table'), ('image', 'Image'), ('text', 'Text'), ('instruction', 'Instruction')], max_length=20),
        ),
        migrations.AlterField(
            model_name='examnode',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='examnode',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='core.paper'),
        ),
        migrations.AlterField(
            model_name='examnode',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.examnode'),
        ),
        migrations.AlterField(
            model_name='examnode',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='examnode',
            index=models.Index(fields=['paper', 'node_type'], name='core_examno_paper_i_3b1059_idx'),
        ),
        migrations.AddIndex(
            model_name='examnode',
            index=models.Index(fields=['paper', 'number'], name='core_examno_paper_i_686969_idx'),
        ),
    ]
