# Generated by Django 5.2.1 on 2025-07-21 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_paper_is_randomized'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_id', models.CharField(max_length=50, unique=True)),
                ('number', models.CharField(blank=True, max_length=20)),
                ('marks', models.CharField(blank=True, max_length=10)),
                ('text', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_id', models.CharField(max_length=50, unique=True)),
                ('number', models.CharField(blank=True, max_length=20)),
                ('marks', models.CharField(blank=True, max_length=10)),
                ('text', models.TextField(blank=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='core.paper')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(max_length=20)),
                ('text', models.TextField(blank=True)),
                ('rows', models.JSONField(blank=True, null=True)),
                ('data_uri', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('child_block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='core.questionchild')),
                ('parent_block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='core.questionparent')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='questionchild',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.questionparent'),
        ),
    ]
