# Generated by Django 5.2.1 on 2025-06-18 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_examanswer_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='examanswer',
            unique_together={('user', 'question')},
        ),
    ]
