# Generated by Django 5.2.1 on 2025-07-23 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_questionchild_questionparent_questioncontent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='is_selected_by_etqa',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Submitted to Moderator', 'Submitted to Moderator'), ('Returned for Changes', 'Returned for Changes'), ('Approved by Moderator', 'Approved by Moderator'), ('Submitted to QCTO', 'Submitted to QCTO'), ('Approved by QCTO', 'Approved by QCTO'), ('Submitted to ETQA', 'Submitted to ETQA'), ('Released to students', 'Released to students'), ('Rejected', 'Rejected')], default='Pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('default', 'Awaiting Activation'), ('admin', 'Administrator'), ('assessor_dev', 'Assessor (Developer)'), ('moderator', 'Moderator (Developer)'), ('qcto', 'QCTO Validator'), ('etqa', 'ETQA'), ('learner', 'Learner'), ('assessor_marker', 'Assessor (Marker)'), ('internal_mod', 'Internal Moderator'), ('external_mod', 'External Moderator (QALA)'), ('assessment_center', 'Assessment Center')], default='learner', max_length=30),
        ),
    ]
