# Generated by Django 5.2.1 on 2025-07-23 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_assessment_is_selected_by_etqa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='number_of_learners',
        ),
    ]
