# Generated by Django 5.2.1 on 2025-06-19 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_examanswer_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='examanswer',
            unique_together={('user', 'question', 'attempt_number')},
        ),
    ]
